services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: DEV2024#
      MYSQL_DATABASE: library_management
    ports:
      - "3361:3306"

  app:
    image: library-management:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3360/library_management
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: DEV2024#
    ports:
      - "9000:8080"
    volumes:
      - app-logs:/app/logs
    depends_on:
      - db

volumes:
  app-logs:

# docker stack deploy -c docker-compose.yml library-management
# docker stack rm library-management
